server {
    listen 8080;
    server_name icarus-regav.ddns.net;

    location / {
        proxy_pass http://wine-front:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://wine-api:3000/;
        proxy_set_header Host $host;
    }
}